import { Produtos } from '../interface/produtos';
import { Categorias } from './categorias';

export const PRODUTOS: Produtos[] = [
  {
    id: 1,
    name: 'AH168456',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[0]],
    imageUrl: 'produtos/AH168456.png',
  },
  {
    id: 2,
    name: '71370165',
    category: Categorias.masseyFerguson.name,
    subcategories: [Categorias.masseyFerguson.subcategories[0]],
    imageUrl: 'produtos/71370165.png',
  },
  {
    id: 3,
    name: 'RE586976',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[0]],
    imageUrl: 'produtos/RE586976.jpg',
  },
  {
    id: 3,
    name: 'AH223951',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[0]],
    imageUrl: 'produtos/AH223951.jpeg',
  },
  {
    id: 3,
    name: '247991A1',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[1]],
    imageUrl: 'produtos/247991A1.png',
  },
  {
    id: 3,
    name: 'RE520465',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[1]],
    imageUrl: 'produtos/RE520465.jpg',
  },
  {
    id: 3,
    name: '71410727',
    category: Categorias.masseyFerguson.name,
    subcategories: [Categorias.masseyFerguson.subcategories[0]],
    imageUrl: 'produtos/71410727.jpeg',
  },
  {
    id: 3,
    name: '1615682500',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1615682500.jpeg',
  },
  {
    id: 3,
    name: '8501111',
    category: Categorias.pacarregadeira.name,
    subcategories: [Categorias.pacarregadeira.subcategories[0]],
    imageUrl: 'produtos/8501111.jpeg',
  },
  {
    id: 3,
    name: '102862021',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/102862021.jpeg',
  },

  {
    id: 3,
    name: '87802627',
    category: Categorias.newHolland.name,
    subcategories: [Categorias.newHolland.subcategories[2]],
    imageUrl: 'produtos/87802627.jpg',
  },
  {
    id: 3,
    name: '1020507200',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[2]],
    imageUrl: 'produtos/1020507200.jpg',
  },
  {
    id: 3,
    name: '1028657736',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1028657736.jpg',
  },
  {
    id: 3,
    name: '1028819420',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1028819420.jpg',
  },
  {
    id: 3,
    name: '1031300041',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1031300041.jpg',
  },
  {
    id: 3,
    name: '1604076100',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1604076100.jpg',
  },
  {
    id: 3,
    name: '1619377301',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[2]],
    imageUrl: 'produtos/1619377301.jpg',
  },
  {
    id: 3,
    name: '1626044200',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1626044200.jpg',
  },
  {
    id: 3,
    name: '1615667500',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1615667500.jpg',
  },
  {
    id: 3,
    name: '619380400',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/619380400.jpg',
  },
  {
    id: 3,
    name: '1626510900',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/1626510900.jpg',
  },
  {
    id: 3,
    name: '02656839',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/02656839.jpg',
  },
  {
    id: 3,
    name: '1202871800',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[2]],
    imageUrl: 'produtos/1202871800.jpg',
  },
  {
    id: 3,
    name: '1202871800',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[2]],
    imageUrl: 'produtos/1202871800.jpg',
  },
  {
    id: 3,
    name: 'M43',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/M43.jpg',
  },
  {
    id: 3,
    name: 'M26/27',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/M26-27.jpg',
  },
  {
    id: 3,
    name: '247991A1',
    category: Categorias.compressores.name,
    subcategories: [Categorias.compressores.subcategories[0]],
    imageUrl: 'produtos/247991A1.png',
  },
  {
    id: 3,
    name: '251991A1',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[1]],
    imageUrl: 'produtos/251991A1.jpeg',
  },
  {
    id: 3,
    name: '87396965',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[1]],
    imageUrl: 'produtos/87396965.jpg',
  },
  {
    id: 3,
    name: '450679',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[0]],
    imageUrl: 'produtos/450679.jpg',
  },
  {
    id: 3,
    name: '9511514',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[0]],
    imageUrl: 'produtos/9511514.jpg',
  },
  {
    id: 3,
    name: '9515000',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[0]],
    imageUrl: 'produtos/9515000.jpg',
  },
  {
    id: 3,
    name: '9811514',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[0]],
    imageUrl: 'produtos/9811514.jpg',
  },
  {
    id: 3,
    name: '48012333',
    category: Categorias.case.name,
    subcategories: [Categorias.case.subcategories[0]],
    imageUrl: 'produtos/48012333.jpeg',
  },
  {
    id: 3,
    name: 'AH163157',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[0]],
    imageUrl: 'produtos/AH163157.jpg',
  },
  {
    id: 3,
    name: 'RE321069',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[2]],
    imageUrl: 'produtos/RE321069.PNG',
  },
  {
    id: 3,
    name: 'RE516509',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[1]],
    imageUrl: 'produtos/RE516509.PNG',
  },
  {
    id: 3,
    name: 'R111173',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[2]],
    imageUrl: 'produtos/R111173.jpg',
  },
  {
    id: 3,
    name: 'RE12820',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[1]],
    imageUrl: 'produtos/RE12820.PNG',
  },
  {
    id: 3,
    name: 'RE70472',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[0]],
    imageUrl: 'produtos/RE70472.jpg',
  },
  {
    id: 3,
    name: 'AH168456',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[0]],
    imageUrl: 'produtos/AH168456.png',
  },
  {
    id: 3,
    name: '00051',
    category: Categorias.pacarregadeira.name,
    subcategories: [Categorias.pacarregadeira.subcategories[0]],
    imageUrl: 'produtos/00051.jpg',
  },
  {
    id: 3,
    name: '00031',
    category: Categorias.pacarregadeira.name,
    subcategories: [Categorias.pacarregadeira.subcategories[0]],
    imageUrl: 'produtos/00031.jpg',
  },
  {
    id: 3,
    name: '355829A2',
    category: Categorias.pacarregadeira.name,
    subcategories: [Categorias.pacarregadeira.subcategories[0]],
    imageUrl: 'produtos/355829A2.jpg',
  },
  {
    id: 3,
    name: 'RE59827',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[1]],
    imageUrl: 'produtos/RE59827.jpg',
  },
  {
    id: 3,
    name: 'RE584547',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[1]],
    imageUrl: 'produtos/RE584547.PNG',
  },
  {
    id: 3,
    name: 'RE580643',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[1]],
    imageUrl: 'produtos/RE580643.PNG',
  },
  {
    id: 3,
    name: 'RE586742',
    category: Categorias.johnDeere.name,
    subcategories: [Categorias.johnDeere.subcategories[3]],
    imageUrl: 'produtos/RE586742.PNG',
  },
];
